on:
  push:
    branches:
      - main # Change this to your default branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: cd
        run: |
          sudo chmod -R 777 docs
          cd ./docs
          pwd

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Use Node.js 18 here

      - name: Install dependencies and Build site
        run: |
          sudo npm install
          sudo npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Change this if your build output directory is different